lwc-working-time-tracking/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PRO-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <label>Cost Center</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Finances</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
                <isActive>false</isActive>
                <label>Financial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

lwc-working-time-tracking/force-app/main/default/objects/Project__c/fields/ProjectOwner__c.field-meta.xml
<CustomField>
    <fullName>ProjectOwner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Owning Projects</relationshipLabel>
    <relationshipName>Owning_Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeTrackingLog__c/TimeTrackingLog__c.object-meta.xml
<CustomObject>
    <label>Time Tracking Log</label>
    <nameField>
        <displayFormat>TTL-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Tracking Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeTrackingLog__c/fields/Collaborator__c.field-meta.xml
<CustomField>
    <fullName>Collaborator__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Collaborator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Collaborator Time Tracking Logs</relationshipLabel>
    <relationshipName>Collaborator_TimeTrackingLogs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeTrackingLog__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>End Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/TimeTrackingLog__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Time Tracking Logs</relationshipLabel>
    <relationshipName>Project_TimeTrackingLogs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

lwc-working-time-tracking/force-app/main/default/objects/TimeTrackingLog__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Start Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

lwc-working-time-tracking/force-app/main/default/objects/TimeTrackingLog__c/fields/TaskDescription__c.field-meta.xml
<CustomField>
    <fullName>TaskDescription__c</fullName>
    <label>Task Description</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TimeTrackingLog__c/fields/TotalTime__c.field-meta.xml
<CustomField>
    <fullName>TotalTime__c</fullName>
    <formula>(EndTime__c - StartTime__c) / 3600000</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TimeTrackingLogController.cls
public with sharing class TimeTrackingLogController {

  public class FiltersWrapper {
      public String projectId { get; set; }
      public String collaboratorId { get; set; }
      public String department { get; set; }
      public String startDate { get; set; }
      public String endDate { get; set; }
    }

  private static String timeTrackingQuery ='SELECT Id, Name, Date__c, StartTime__c, EndTime__c, TaskDescription__c, ' + 
                'Collaborator__r.Name, Collaborator__r.Id, TotalTime__c, ' +
                'Project__r.Name, Project__r.Department__c, Project__r.ProjectOwner__r.Name, Project__r.CostCenter__c ' + 
                'FROM TimeTrackingLog__c';

  @AuraEnabled
  public static List<TimeTrackingLog__c> fetchFilteredRecords(String jsonFilters) {
    try {
      FiltersWrapper filtersWrapper = (FiltersWrapper) JSON.deserialize(jsonFilters, FiltersWrapper.class);
      String whereClause = getWhereClause(filtersWrapper);
      return Database.query(timeTrackingQuery + whereClause);
    } catch (Exception e) {
      throw new AuraHandledException(
        'Error deserializing filter parameters: ' + e.getMessage() + '. >> Filters: ' + jsonFilters
      );
    }
  }

  private static String getWhereClause(FiltersWrapper filtersWrapper) {
    String whereClause = ' WHERE Project__r.Active__c = true';
    if (!String.isEmpty(filtersWrapper.collaboratorId)) {
      whereClause += ' AND Collaborator__r.Name = \'' + filtersWrapper.collaboratorId + '\'';
    }
    if (
      !String.isEmpty(filtersWrapper.projectId) &&
      !'All'.equals(filtersWrapper.projectId)
    ) {
      whereClause += ' AND Project__r.Id = \'' + filtersWrapper.projectId + '\'';
    }
    if (!String.isEmpty(filtersWrapper.department)) {
      whereClause += ' AND Project__r.Department__c = \'' + filtersWrapper.department + '\'';
    }
    if (!String.isEmpty(filtersWrapper.startDate)) {
      whereClause += ' AND Date__c >= ' + filtersWrapper.startDate;
    }
    if (!String.isEmpty(filtersWrapper.endDate)) {
      whereClause += ' AND Date__c <= ' + filtersWrapper.endDate;
    }
    whereClause += ' ORDER BY Date__c DESC, StartTime__c ASC';
    return whereClause;
  }

  @AuraEnabled(cacheable=true)
  public static List<Project__c> getAllProjects() {
    return [
      SELECT Id, Name, Department__c, ProjectOwner__r.Name, CostCenter__c
      FROM Project__c
    ];
  }
}